# Site settings
title: GEEK-LAND | AVISHKA PERERA
description: Avishka Perera's blog about all things GEEK..well mostly CODING..
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://avishkaperera.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Avishka Perera
user_description: Coder | Tech Enthusiast | SE Graduate | Peterite | Entrepreneur | Photographer
email: avishkaperera4@gmail.com
twitter_username: avishka_perera
github_username:  avishkaperera
gplus_username:  +AvishkaPerera
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
